# Generated by hand for the AutoDrive project
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(help_text="URL-friendly identifier for lookups", unique=True)),
                ("name_en", models.CharField(max_length=120)),
                ("name_ar", models.CharField(max_length=120)),
                ("price_en", models.CharField(max_length=120)),
                ("price_ar", models.CharField(max_length=120)),
                ("feature_one_en", models.CharField(max_length=160)),
                ("feature_one_ar", models.CharField(max_length=160)),
                ("feature_two_en", models.CharField(max_length=160)),
                ("feature_two_ar", models.CharField(max_length=160)),
                ("feature_three_en", models.CharField(max_length=160)),
                ("feature_three_ar", models.CharField(max_length=160)),
                ("image_url", models.URLField()),
            ],
            options={"ordering": ["name_en"]},
        ),
    ]
